version: '3'
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  svelte-app:
    build:
      context: ./app
    container_name: svelte-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - pocketbase